import streamlit as st
import requests
import datetime
import os
import textwrap

# from exception.exceptions import TradingBotException
import sys

# Do not include a trailing slash: adding the route below would otherwise request
# `//query`, which is not the FastAPI route served by the deployed backend.
BASE_URL = os.getenv("BACKEND_URL", "http://127.0.0.1:8000").rstrip("/")

st.set_page_config(
    page_title="🌍 Travel Planner Agentic Application",
    page_icon="🌍",
    layout="centered",
    initial_sidebar_state="expanded",
)

st.title("🌍 Travel Planner Agentic Application")

# Initialize chat history
if "messages" not in st.session_state:
    st.session_state.messages = []

# Display chat history
st.header("How can I help you in planning a trip? Let me know where do you want to visit.")

# Chat input box at bottom
with st.form(key="query_form", clear_on_submit=True):
    user_input = st.text_input("User Input", placeholder="e.g. Plan a trip to Goa for 5 days")
    submit_button = st.form_submit_button("Send")

if submit_button and user_input.strip():
    try:
        # # Show user message
        # Show thinking spinner while backend processes
        with st.spinner("Bot is thinking..."):
            payload = {"question": user_input}
            response = requests.post(f"{BASE_URL}/query", json=payload, timeout=300)

        if response.status_code == 200:
            answer = response.json().get("answer", "No answer returned.")
            markdown_content = textwrap.dedent(f"""\
            # 🌍 AI Travel Plan

            **Generated:** {datetime.datetime.now().strftime('%Y-%m-%d at %H:%M')}
            **Created by:** Mana's Travel Agent

            ---

            {answer}

            ---

            *This travel plan was generated by AI. Please verify all information, especially prices, operating hours, and travel requirements before your trip.*
            """).strip()
            st.markdown(markdown_content)
        else:
            st.error(" Bot failed to respond: " + response.text)

    except requests.RequestException as e:
        st.error(f"Could not reach the travel-planner backend: {e}")
